package org.localareadelivery.distributorapp.Model;

import android.os.Parcel;
import android.os.Parcelable;

import java.util.List;



public class Shop implements Parcelable{
	

	int shopID;

	Distributor distributor;
	
	String shopName;
	
	//This is the distance upto which shop can deliver its items
	double radiusOfService;
	
	// the average of all the ratings given by the end users
	// the average rating is updated whenever a user rates a shop
	double averageRating;
	
	// latitude and longitude for storing the location of the shop
	double latitude;
	double longitude;
	
	// delivery charger per order 
	double deliveryCharges;

	int distributorID;

	String imagePath;



	public String getImagePath() {
		return imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	public int getDistributorID() {
		return distributorID;
	}

	public void setDistributorID(int distributorID) {
		this.distributorID = distributorID;
	}


	public double getRadiusOfService() {
		return radiusOfService;
	}

	public void setRadiusOfService(double radiusOfService) {
		this.radiusOfService = radiusOfService;
	}

	public double getAverageRating() {
		return averageRating;
	}

	public void setAverageRating(double averageRating) {
		this.averageRating = averageRating;
	}

	public double getDeliveryCharges() {
		return deliveryCharges;
	}

	public void setDeliveryCharges(double deliveryCharges) {
		this.deliveryCharges = deliveryCharges;
	}

	public double getLatitude() {
		return latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	public double getLongitude() {
		return longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	public int getShopID() {
		return shopID;
	}

	public void setShopID(int shopID) {
		this.shopID = shopID;
	}

	public String getShopName() {
		return shopName;
	}

	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	public Distributor getDistributor() {
		return distributor;
	}

	public void setDistributor(Distributor distributor) {
		this.distributor = distributor;
	}


	public Shop(Distributor distributor, String shopName, int radiusOfService, int averageRating, double latitude,
				double longitude, int deliveryCharges) {


		super();

		this.shopName = shopName;
		this.radiusOfService = radiusOfService;
		this.averageRating = averageRating;
		this.latitude = latitude;
		this.longitude = longitude;
		this.deliveryCharges = deliveryCharges;
	}

	public Shop() {
		super();
		// TODO Auto-generated constructor stub
	}

	@Override
	public String toString() {
		super.toString();


		String resultMessage = "ID: " + this.getShopID()
				+ "\n\nShop Name : " + this.getShopName()
				+ "\n\nRadius Of Service : " + this.getRadiusOfService()
				+ "\n\nLatitude : " + this.getLatitude()
				+ "\n\nLongitude : " + this.getLongitude()
				+ "\n\nAverage Rating : " + this.getAverageRating()
				+ "\n\nDelivery Charges : " + this.getDeliveryCharges()
				+ "\n\nDistributor ID : " + this.getDistributorID()
				+ "\n\nImage Path : " + this.getImagePath();


		return resultMessage;
	}





	// Autogenerated parcelable implementation



	protected Shop(Parcel in) {
		shopID = in.readInt();
		shopName = in.readString();
		radiusOfService = in.readDouble();
		averageRating = in.readDouble();
		latitude = in.readDouble();
		longitude = in.readDouble();
		deliveryCharges = in.readDouble();
		distributorID = in.readInt();
		imagePath = in.readString();
	}

	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeInt(shopID);
		dest.writeString(shopName);
		dest.writeDouble(radiusOfService);
		dest.writeDouble(averageRating);
		dest.writeDouble(latitude);
		dest.writeDouble(longitude);
		dest.writeDouble(deliveryCharges);
		dest.writeInt(distributorID);
		dest.writeString(imagePath);
	}

	@Override
	public int describeContents() {
		return 0;
	}

	public static final Creator<Shop> CREATOR = new Creator<Shop>() {
		@Override
		public Shop createFromParcel(Parcel in) {
			return new Shop(in);
		}

		@Override
		public Shop[] newArray(int size) {
			return new Shop[size];
		}
	};



}
